### PR TITLE
Fix problem when <i> class contains non-famfamfam classes

### PR DESCRIPTION
**Pull request by TintinJS**
For example this :
`<i class="any-class famfamfam-flag-us"></i>` didn't work.

### CODE REVIEW

**Comment by walane** [comment]
Anyone can check and merge ? :)

**Comment by tkrotoff** [comment]
@walane 
I've checked how Bootstrap 2.3.2 did it: https://github.com/twbs/bootstrap/blob/v2.3.2/less/sprites.less#L17
```CSS
[class^="icon-"],
[class*=" icon-"] {
  ...
}
```

Same for old FontAwesome 3.2.1: https://github.com/FortAwesome/Font-Awesome/blob/v3.2.1/less/bootstrap.less

So I think it would be wiser to have this:
```CSS
[class^="famfamfam-flag"],
[class*=" famfamfam-flag"] {
  ...
}
```

**Comment by walane** [comment]
Indeed it's better !
I've updated the pull request ;)

**Comment by tkrotoff** [comment]
Thx!

**Pull request merged**
